### ISSUE TITLE
Question 3: Shoveling into a string

### ISSUE THREAD

**Issue by jldivemaster** [learn-co-curriculum/mutability-quiz#6]
Question 3 has us shoveling into a string, which is not allowed (right?).

**Comment by maxwellbenton** [comment]
Hi @jldivemaster,

Good question. This is valid Ruby, and in fact, it looks like shoveling is preferred in some situations due to speed and memory benefits: https://stackoverflow.com/questions/4684446/why-is-the-shovel-operator-preferred-over-plus-equals-when-building-a

Since the code snippet provided in this question does produce one of the quiz answer options, I am going to go ahead and close this issue, but please feel free to re-open if you do not feel this issue is resolved.
